berandaCardsInfo = [
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 1",
    title: "Memulai Pemrograman dengan Flutter",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/android-app.png",
    langkah: "Langkah 2",
    title: "Belajar Membuat Aplikasi Android untuk Pemula",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 3",
    title: "Belajar Fundamental Aplikasi Android",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 4",
    title: "Belajar Pengembangan Aplikasi Android",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/android-app.png",
    langkah: "Langkah 5",
    title: "Menerapkan prinsip Pemrograman SOLID",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 6",
    title: "Menjadi Android Developer tingkat Expert",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
];
ruangKelasCardsInfo = [
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 1",
    title: "Memulai Pemrograman dengan Flutter",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/android-app.png",
    langkah: "Langkah 2",
    title: "Belajar Membuat Aplikasi Android untuk Pemula",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 3",
    title: "Belajar Fundamental Aplikasi Android",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 4",
    title: "Belajar Pengembangan Aplikasi Android",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 5",
    title: "Menerapkan prinsip Pemrograman SOLID",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 6",
    title: "Menjadi Android Developer tingkat Expert",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 7",
    title: "Memulai Pemrograman dengan Flutter",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/android-app.png",
    langkah: "Langkah 8",
    title: "Belajar Membuat Aplikasi Android untuk Pemula",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 9",
    title: "Belajar Fundamental Aplikasi Android",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 10",
    title: "Belajar Pengembangan Aplikasi Android",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 11",
    title: "Menerapkan prinsip Pemrograman SOLID",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
  {
    imageUrl: "assets/flutter.png",
    langkah: "Langkah 12",
    title: "Menjadi Android Developer tingkat Expert",
    pfp: "assets/pfp.png",
    name: "Marchella Angelina",
    job: "flutter developer",
  },
];
module.exports = { berandaCardsInfo, ruangKelasCardsInfo };
